name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://qc4.androidfilehost.com/dl/mUxwQuFwpkiu_CWBm9m5Rw/1589226136/4349826312261801029/xiaomi.eu_multi_MI9SE_20.5.7_v12-10.zip
  ROM_NAME: MIUI
  ROM_TYPE: b
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       #- name: Clean Up
       #  run: |
       #    docker rmi `docker images -q`
       #    sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
       #    sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
       #    sudo -E apt-get update
       #    sudo -E apt-get -y autoremove --purge
       #    sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code and Setting up ErfanGSI requirements
         run: |
              git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME -$ROM_TYPE
       
       - name: Zip GSI  
         run: |
              mkdir final
              current=`date "+%Y-%m-%d %H:%M:%S"`  
              timeStamp=`date -d "$current" +%s`   
              currentTimeStamp=$((timeStamp*1000+`date "+%N"`/1000000)) 
              zip -r final/GSI-$currentTimeStamp.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
       
       - name: Upload GSI to BitSend
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit final/GSI.zip

         
            
